[project]
name = "common_metrics_on_video_quality"
version = "0.0.0"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["common_metrics_on_video_quality"]
